import { sql } from '../db'
import { settingsService } from './settings.service'

class HistoryCleanupService {
    private intervalId: Timer | null = null
    private readonly CHECK_INTERVAL_MS = 60 * 60 * 1000 // Check every hour

    // Default Retention in Days
    private readonly DEFAULT_RETENTION_DAYS = 90

    start() {
        console.log(`🧹 [Cleanup] Starting History Cleanup Service (Default: ${this.DEFAULT_RETENTION_DAYS} days)...`)

        // Run immediately on start (or delay slightly to let app boot)
        setTimeout(() => this.runCleanup(), 10000)

        // Then schedule periodic checks
        this.intervalId = setInterval(() => {
            this.runCleanup()
        }, this.CHECK_INTERVAL_MS)
    }

    stop() {
        if (this.intervalId) {
            clearInterval(this.intervalId)
            this.intervalId = null
        }
    }

    async runCleanup() {
        try {
            // Fetch configuration
            const settings = await settingsService.getSettings()
            const retentionDays = Number(settings['history_retention_days']) || this.DEFAULT_RETENTION_DAYS

            // Calculate cutoff date
            const cutoffDate = new Date()
            cutoffDate.setDate(cutoffDate.getDate() - retentionDays)

            console.log(`🧹 [Cleanup] Running cleanup. Retention: ${retentionDays} days. Cutoff: ${cutoffDate.toISOString()}...`)

            // 1. Get all dynamic tables
            const tables = await sql`
                SELECT DISTINCT report_table_name 
                FROM points 
                WHERE report_table_name IS NOT NULL
            `

            console.log(`🧹 [Cleanup] Found ${tables.length} tables to clean...`)

            let tablesCleaned = 0
            let errors = 0

            // 2. Iterate and Clean
            for (const t of tables) {
                const tableName = t.report_table_name
                try {
                    // Using sql.unsafe here as table name is dynamic. 
                    // report_table_name is trusted internal data (generated by our service code).
                    await sql.unsafe(`
                        DELETE FROM ${tableName}
                        WHERE timestamp < '${cutoffDate.toISOString()}'
                    `)
                    tablesCleaned++
                } catch (tableErr) {
                    console.error(`⚠️ [Cleanup] Failed to clean table ${tableName}:`, tableErr)
                    errors++
                }
            }

            console.log(`✅ [Cleanup] Processed ${tablesCleaned} tables with ${errors} errors.`)

        } catch (error) {
            console.error('❌ [Cleanup] Failed to clean old logs:', error)
        }
    }
}

export const historyCleanupService = new HistoryCleanupService()
